openapi: 3.0.3
info:
  title: ''
  version: 0.0.0
paths:
  /api/schema/:
    get:
      operationId: api_schema_retrieve
      description: |-
        OpenApi3 schema for this API. Format can be selected via content negotiation.

        - YAML: application/vnd.oai.openapi
        - JSON: application/vnd.oai.openapi+json
      parameters:
      - in: query
        name: format
        schema:
          type: string
          enum:
          - json
          - yaml
      - in: query
        name: lang
        schema:
          type: string
          enum:
          - af
          - ar
          - ar-dz
          - ast
          - az
          - be
          - bg
          - bn
          - br
          - bs
          - ca
          - ckb
          - cs
          - cy
          - da
          - de
          - dsb
          - el
          - en
          - en-au
          - en-gb
          - eo
          - es
          - es-ar
          - es-co
          - es-mx
          - es-ni
          - es-ve
          - et
          - eu
          - fa
          - fi
          - fr
          - fy
          - ga
          - gd
          - gl
          - he
          - hi
          - hr
          - hsb
          - hu
          - hy
          - ia
          - id
          - ig
          - io
          - is
          - it
          - ja
          - ka
          - kab
          - kk
          - km
          - kn
          - ko
          - ky
          - lb
          - lt
          - lv
          - mk
          - ml
          - mn
          - mr
          - ms
          - my
          - nb
          - ne
          - nl
          - nn
          - os
          - pa
          - pl
          - pt
          - pt-br
          - ro
          - ru
          - sk
          - sl
          - sq
          - sr
          - sr-latn
          - sv
          - sw
          - ta
          - te
          - tg
          - th
          - tk
          - tr
          - tt
          - udm
          - ug
          - uk
          - ur
          - uz
          - vi
          - zh-hans
          - zh-hant
      tags:
      - api
      security:
      - basicAuth: []
      - cookieAuth: []
      - {}
      responses:
        '200':
          content:
            application/vnd.oai.openapi:
              schema:
                type: object
                additionalProperties: {}
            application/yaml:
              schema:
                type: object
                additionalProperties: {}
            application/vnd.oai.openapi+json:
              schema:
                type: object
                additionalProperties: {}
            application/json:
              schema:
                type: object
                additionalProperties: {}
          description: ''
  /auth/:
    get:
      operationId: auth_retrieve
      description: |-
        View to return user and auth information.
        :param request: WSGIRequest object containing user and auth information
        :return: Response with user and auth information
      tags:
      - auth
      security:
      - cookieAuth: []
      - basicAuth: []
      responses:
        '200':
          description: No response body
  /create-room/:
    post:
      operationId: create_room_create
      description: |-
        Create a new room.
        :param request: {user, data}
        :return: Response with success or error message
      tags:
      - create-room
      security:
      - basicAuth: []
      - cookieAuth: []
      responses:
        '200':
          description: No response body
  /join-room/:
    post:
      operationId: join_room_create
      description: |-
        Join an existing room by code.
        :param request: {user, data}
        :return: Response with success or error message
      tags:
      - join-room
      security:
      - basicAuth: []
      - cookieAuth: []
      responses:
        '200':
          description: No response body
  /login/:
    post:
      operationId: login_create
      description: |-
        Handle user login.
        :param request: {username, password}
        :return: Response with success or error message
      tags:
      - login
      security:
      - basicAuth: []
      - cookieAuth: []
      - {}
      responses:
        '200':
          description: No response body
  /logout/:
    post:
      operationId: logout_create
      description: |-
        Handle user logout.
        :param request: {user}
        :return: Response with success or error message
      tags:
      - logout
      security:
      - basicAuth: []
      - cookieAuth: []
      - {}
      responses:
        '200':
          description: No response body
  /register/:
    post:
      operationId: register_create
      description: |-
        Handle user registration.
        :param request: {username, password}
        :return: Response with success or error message
      tags:
      - register
      security:
      - basicAuth: []
      - cookieAuth: []
      - {}
      responses:
        '200':
          description: No response body
  /room/{code}/:
    get:
      operationId: room_retrieve
      description: |-
        Get details of a room by code.
        :param code: str
        :param request: {code}
        :return: Response with room details or error message
      parameters:
      - in: path
        name: code
        schema:
          type: string
        required: true
      tags:
      - room
      security:
      - basicAuth: []
      - cookieAuth: []
      responses:
        '200':
          description: No response body
components:
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic
    cookieAuth:
      type: apiKey
      in: cookie
      name: sessionid
